# Generated by Django 5.0.2 on 2024-03-24 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(max_length=100)),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('descripcion_cargo', models.CharField(max_length=100)),
                ('salario_cargo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('extra_dec', models.BooleanField(default=False)),
                ('extra_jun', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_codigo_postal', models.CharField(max_length=100)),
                ('poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.poblacion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.fabrica')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.puesto')),
            ],
        ),
        migrations.AddField(
            model_name='puesto',
            name='salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestions.salario'),
        ),
    ]
